//  LocalizedKey.swift
//  All_Pets
//
//  Created by Gerardo Bautista Castañeda on 09/08/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//

extension String {
    static let MsgLoader = "Cargando.."
    static let MsgButtonLogin = "Iniciar sesión"
    static let MsgButtonSignUp = "Registrarse"
    static let MsgEmailLogin = "Correo electrónico"
    static let MsgName = "Nombre"
    static let MsgFirstLastName = "Apellido paterno"
    static let MsgSecondLastName = "Apellido materno"
    static let MsgPasswordLogin = "Contraseña"
    static let MsgRepeatLogin = "Confirmar contraseña"
    static let MsgForgotPassword = "¿Olvidaste tu contraseña?"
    static let MsgSignUpTitle = "¿No tienes una cuenta?"
    static let MsgSignUp = "Registrarse"
    static let MsgAcept = "Aceptar"
    static let MsgWarning = "¡Alerta!"
    static let MsgPasswordOrUserInvalid = "El usuario ó contraseña son incorrectos"
    static let MsgFormIncomplete = "Campo obligatorio"
    static let MsgSignOut = "Cerrar sesión"
    static let MsgSignUpTitleHeader = "Crear cuenta nueva"
    static let MsgTitlePetRegister = "Selecciona tu mascota"
    static let MsgSelected = "Seleccionado"
    static let MsgAdd = "Agregar"
    static let MsgUploadProfilePhoto = "Subir foto de perfil"
    static let MsgSelectTypePet = "Seleccione una raza"
    static let MsgDateBirthDay = "Fecha de nacimiento"
    static let MsgAddPet = "Añadir Mascota"
    static let MsgHello = "Hola"
    static let MsgAddNewPet = "Agregar mascota"
    static let MsgNoPetsRegistered = "No tienes mascotas registradas"
    static let MsgRequestDigitalProof = "Solicitar constancia digital"
    static let MsgProceedings = "Expediente"
    static let MsgVaccinationCard = "Cartilla"
    static let MsgDate = "Fecha"
    static let MsgProfessionalLiscense = "CP Médico"
    static let MsgNoPendingAppointments = "No tienes citas pendientes"
    static let MsgPendingAppointments = "Tienes una cita pendiente de ser confirmada por la clínica"
    static let MsgHaveAnAppointment = "Tiene una cita el"
    static let MsgNoLocalization = "Localización NO Aceptada ❌"
    static let MsgAceptLocalization = "Pulsa para aceptar la autorización de Localización"
    static let MsgSendAlert = "Enviar alerta"
    static let WordJoin = "y"
    static let WordPets = "Mascotas"
    static let MsgTitleVeterin = "Acceso rápido a especialistas"
    static let WordsSpecificInquiries = "Consultas específicas"
    static let WordSpecialities = "Especialidades"
    static let WordApply = "Aplicar"
    static let WordsToAskForADate = "Solicitar cita"
    static let WordOffice = "Consultorio"
    static let WordsNearbyOffice = "Consultorio cercano"
    static let WordSchedule = "Horario"
    static let WordsTheyServe = "Atienden a"
    static let WordContact = "Contacto"
    static let WordNumber = "Número"
}
