//  LocalizedKey.swift
//  All_Pets
//
//  Created by Gerardo Bautista Castañeda on 09/08/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//

extension String {
    static let MsgRepeatLogin = "Confirmar contraseña"
    static let MsgForgotPassword = "¿Olvidaste tu contraseña?"
    static let MsgSignUpTitle = "¿No tienes una cuenta?"
    static let MsgSignUp = "Registrarse"
    static let MsgAcept = "Aceptar"
    static let MsgWarning = "¡Alerta!"
    static let MsgPasswordOrUserInvalid = "El usuario ó contraseña son incorrectos"
    static let MsgFormIncomplete = "Campo obligatorio"
    static let MsgSignOut = "Cerrar sesión"
    static let MsgSignUpTitleHeader = "Crear cuenta nueva"
    static let MsgTitlePetRegister = "Selecciona tu mascota"
    static let MsgSelected = "Seleccionado"
    static let MsgNoPetsRegistered = "No tienes mascotas registradas"
    static let MsgRequestDigitalProof = "Solicitar constancia digital"
    static let MsgProceedings = "Expediente"
    static let MsgVaccinationCard = "Cartilla"
    static let MsgDate = "Fecha"
    static let MsgProfessionalLiscense = "CP Médico"
    static let MsgNoPendingAppointments = "No tienes citas pendientes"
    static let MsgPendingAppointments = "Tienes una cita pendiente de ser confirmada por la clínica"
    static let MsgHaveAnAppointment = "Tiene una cita el"
    static let MsgNoLocalization = "Localización NO Aceptada ❌"
    static let MsgAceptLocalization = "Pulsa para aceptar la autorización de Localización"
    static let MsgSendAlert = "Enviar alerta"
    static let WordJoin = "y"
    static let WordPets = "Mascotas"
    static let MsgTitleVeterin = "Acceso rápido a especialistas"
    static let WordsSpecificInquiries = "Consultas específicas"
    static let WordSpecialities = "Especialidades"
    static let WordApply = "Aplicar"
    static let WordsToAskForADate = "Solicitar cita"
    static let WordOffice = "Consultorio"
    static let WordsNearbyOffice = "Consultorio cercano"
    static let WordSchedule = "Horario"
    static let WordsTheyServe = "Atienden a"
    static let WordContact = "Contacto"
    static let WordNumber = "Número"
    static let WordsDateCite = "Fecha de cita"
    static let WordsSelectSchedule = "Seleccionar horario"
    static let WordsSelectTheReason = "Selecciona el motivo"
    static let WordsSelectThePatient = "Selecciona al paciente"
    static let WordsSendRequest = "Enviar solicitud"
    static let WordsNewFunctionalities = "Tendremos nuevas funcionalidades muy pronto"
}
